### ISSUE TITLE
Could we use appcenter.clashx.workers.dev as download link for homebrew cask?

### ISSUE THREAD

**Issue by mrchi** [yichengchen/worker-appcenter#1]
Hi @yichengchen,

Yesterday, the maintainer of [homebrew-cask-version](https://github.com/Homebrew/homebrew-cask-versions) wanted to remove clashx-pro from homebrew cask. Because the download link of clashx-pro `appcenter.vercel.app` returned HTTP 500.

Check this PR for detail https://github.com/Homebrew/homebrew-cask-versions/pull/16023

So would you agree to use `appcenter.clashx.workers.dev` as download link for homebrew cask? I can create a PR for that.

**Comment by yichengchen** [comment]
Argee
